### ISSUE TITLE
User-defined class property assume integer

### ISSUE THREAD

**Issue by kugel-** [mvz/gir_ffi#77]
When defining properties for user-defined classes, gir_ffi assumes the property is an integer type. But properties can be arbitrary, including object and boxed types. The assumption can be seen here:

```
      def layout_specification
        parent_spec = [:parent, superclass::Struct, 0]
        offset = superclass::Struct.size
        fields_spec = properties.flat_map do |pinfo|
          spec = [pinfo.name.to_sym, :int32, offset]
          offset += FFI.type_size(:int32)
          spec
        end
        parent_spec + fields_spec
      end
```

This leads to the following error:
```
(eval):5:in `[]=': no implicit conversion of Gtk::Window into Integer (TypeError)
	from (eval):5:in `object='
	from /home/kugel/.gem/ruby/2.3.0/gems/gir_ffi-0.10.2/lib/gir_ffi/builders/user_defined_builder.rb:118:in `block in property_setter'
```

**Comment by kugel-** [comment]
FTR, I'm registering with this code:

```
  GirFFI.define_type(MyClass) do |info|
    info.g_name = "MyClass"
    info.install_property GObject.param_spec_object("object", "object", "The target object",
                                                    GObject::Object.gtype, 1|2|8)
```

**Comment by kugel-** [comment]
The following improves things. However, the accessor doesn't quite work.

In my code I have a GObjet that with a property of a GBoxed-based type named "plugin-info" (I do `install_property GObject.param_spec_boxed`). `get_name` is a method for that type.

With the patch below the following works:
`obj.get_property("plugin_info").get_name # => Plugin Name`

But the following fails
```
p obj.plugin_info.get_name # =>
../../peas-demo/peas-ruby-demo.rb:53:in `block in <main>'[Thread 0x7fffe8ae1700 (LWP 2746) exited]
: undefined method `get_name' for #<FFI::Pointer address=0x000000012d7900> (NoMethodError)
Did you mean?  get_int
```

Here's the patch (keep in mind that I don't really know what I'm doing :-)

```
diff --git a/lib/gir_ffi/builders/user_defined_builder.rb b/lib/gir_ffi/builders/user_defined_b
index 5ad0992..27dd5b8 100644
--- a/lib/gir_ffi/builders/user_defined_builder.rb
+++ b/lib/gir_ffi/builders/user_defined_builder.rb
@@ -170,8 +170,9 @@ module GirFFI
         parent_spec = [:parent, superclass::Struct, 0]
         offset = superclass::Struct.size
         fields_spec = properties.flat_map do |param_spec|
+          ffi_type = param_spec.class.to_ffi_type
           field_name = param_spec.accessor_name.to_sym
-          spec = [field_name, :int32, offset]
+          spec = [field_name, ffi_type, offset]
           offset += FFI.type_size(:int32)
           spec
         end
```

**Comment by kugel-** [comment]
The following diff is better, it doesn't create corrupt pointers anymore (offset was still wrong). But I still get only the generic FFI::Pointer when using the accessors.

```diff
diff --git a/lib/gir_ffi/builders/user_defined_builder.rb b/lib/gir_ffi/builders/user_defined_builder.rb
index 5ad0992..731bd0f 100644
--- a/lib/gir_ffi/builders/user_defined_builder.rb
+++ b/lib/gir_ffi/builders/user_defined_builder.rb
@@ -86,8 +86,9 @@ module GirFFI
 
       def instance_size
         size = parent_gtype.instance_size
-        properties.each do
-          size += FFI.type_size(:int32)
+        properties.each do |param_spec|
+          ffi_type = param_spec.class.to_ffi_type
+          size += FFI.type_size(ffi_type)
         end
         size
       end
@@ -170,9 +171,10 @@ module GirFFI
         parent_spec = [:parent, superclass::Struct, 0]
         offset = superclass::Struct.size
         fields_spec = properties.flat_map do |param_spec|
+          ffi_type = param_spec.class.to_ffi_type
           field_name = param_spec.accessor_name.to_sym
-          spec = [field_name, :int32, offset]
-          offset += FFI.type_size(:int32)
+          spec = [field_name, ffi_type, offset]
+          offset += FFI.type_size(ffi_type)
           spec
         end
         parent_spec + fields_spec
```

**Comment by mvz** [comment]
Work-in-progress implementation in #78.

**Comment by kugel-** [comment]
@mvz Can this be considered fixed?

**Comment by mvz** [comment]
@kugel- yes, it can!
