### ISSUE TITLE
incompatibility with newer gir-glib: iconv gone causing error on require

### ISSUE THREAD

**Issue by apachelogger** [mvz/gir_ffi#91]
It seems IConv has been retracted from glib's GIR which makes iconv.rb fatally fail to load the IConv class and in turn requiring the gir_ffi.

Affects at least gir-glib 1.56+ (currently due to be shipped in Ubuntu 18.04+)

Apparently removed here:
https://gitlab.gnome.org/GNOME/glib/commit/7759542ee3888badb6eaf1a492b81b5ebc81e5f2

The iconv.rb probably needs to catch at least NameError to fix this.

```
irb(main):001:0> require 'gir_ffi'
NameError: Class IConv not found in namespace GLib
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/gir_ffi/builders/module_builder.rb:50:in `find_namespaced_class_info'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/gir_ffi/builders/module_builder.rb:41:in `build_namespaced_class'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/gir_ffi/module_base.rb:21:in `load_class'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/ffi-glib/iconv.rb:3:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/ffi-glib.rb:17:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.4.0/gems/gir_ffi-0.11.4/lib/gir_ffi.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /usr/local/bin/irb:11:in `<main>'
```

**Comment by mvz** [comment]
Thanks for letting me know, @apachelogger! I fixed this in master and will release soon.
